---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ((concourse-repo))/p-image
    tag: 'latest'

inputs:
- name: yelb-github

params:
  PKS: 
  PKS_USERNAME:
  PKS_PASSWORD:
  PKS_CLUSTER:
  KUBE_CONFIG:
  K8S_NAMESPACE:

run:
  path: yelb-github/pipelines/tasks/scripts/pks-get-kubeconfig.sh