---
resources:
  - name: yelb-github
    type: git
    icon: github-circle
    source:
      uri: https://github.com/devulrix/yelb.git
      branch: master

  - name: db-image
    type: docker-image
    source:
      username: ((harbor-user))
      password: ((harbor-password))
      repository: ((harbor-repo))/yelb-db

  - name: ui-image
    type: docker-image
    source:
      username: ((harbor-user))
      password: ((harbor-password))
      repository: ((harbor-repo))/yelb-ui

  - name: appserver-image
    type: docker-image
    source:
      username: ((harbor-user))
      password: ((harbor-password))
      repository: ((harbor-repo))/yelb-appserver

jobs:
  - name: build-containers
    public: false
    serial: true
    plan: 
      - get: yelb-github
        trigger: true
      - put: db-image
        params:
          build: ./yelb-github/yelb-db 
      - put: ui-image
        params:
          build: ./yelb-github/yelb-ui
      - put: appserver-image
        params:
          build: ./yelb-github/yelb-appserver
