---
resources:
  - name: yelb-github
    type: git
    icon: github-circle
    source:
      uri: https://github.com/devulrix/yelb.git
      branch: master

  - name: yelb-db-image
    type: docker-image
    source:
      email: ((harbor-mail))
      username: ((harbor-user))
      password: ((harbor-password))
      repository: ((harbor-repo))/yelb-db

jobs:
  - name: clone
    public: false
    serial: true
    plan: 
      - get: yelb-github
        trigger: true
      - put: yelb-db-image
        params:
          build: yelb-db 