---
resource_types:
  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource

resources:
  - name: version
    type: semver
    source:
      driver: s3
      initial_version: 0.7.0
      key: ((s3-key))
      endpoint: ((s3-endpoint))
      access_key_id: ((s3-access-key-id))
      secret_access_key: ((s3-secret-access-key))
      bucket: ((verion-s3-bucket))

  - name: yelb-github
    type: git
    icon: github-circle
    source:
      uri: https://github.com/devulrix/yelb.git
      branch: master

  - name: db-image
    type: docker-image
    source:
      username: ((harbor-user))
      password: ((harbor-password))
      repository: ((harbor-repo))/yelb-db

  - name: ui-image
    type: docker-image
    source:
      username: ((harbor-user))
      password: ((harbor-password))
      repository: ((harbor-repo))/yelb-ui

  - name: appserver-image
    type: docker-image
    source:
      username: ((harbor-user))
      password: ((harbor-password))
      repository: ((harbor-repo))/yelb-appserver
  
  - name: send-an-email
    type: email
    source: 
      from: ((mail-from))
      smtp: 
        host: ((mail-host))
        port: ((mail-port))
        username: ((mail-user))
        password: ((mail-password))
      to: [ ((mail-recipient)) ]

jobs:
  - name: build-db-image
    public: false
    serial: true
    plan: 
      - get: yelb-github
        trigger: true
      - get: version
        params: {bump: patch}
      - put: db-image
        params:
          build: ./yelb-github/yelb-db 
          tag_as_latest: true
          tag_file: version/version
    on_error:
      do:
        - put: send-an-email
          params:
            body_text: 'Build error in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
            subject_text: 'Build error in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
    on_failure:
      do:
        - put: send-an-email
          params:
            body_text: 'Build failure in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
            subject_text: 'Build failure in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}' 
  
  - name: build-ui-image
    public: false
    serial: true
    plan:
      - get: yelb-github
        trigger: true
      - get: version
        params: {bump: patch}
      - put: ui-image
        params:
          build: ./yelb-github/yelb-ui
          tag_as_latest: true
          tag_file: version/version
    on_error:
      do:
        - put: send-an-email
          params:
            body_text: 'Build error in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
            subject_text: 'Build error in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
    on_failure:
      do:
        - put: send-an-email
          params:
            body_text: 'Build failure in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
            subject_text: 'Build failure in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}' 

  - name: build-appserver-image
    public: false
    serial: true
    plan:
      - get: yelb-github
        trigger: true
      - get: version
        params: {bump: patch}
      - put: appserver-image
        params:
          build: ./yelb-github/yelb-appserver
          tag_as_latest: true
          tag_file: version/version

    on_error:
      do:
        - put: send-an-email
          params:
            body_text: 'Build error in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
            subject_text: 'Build error in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
    on_failure:
      do:
        - put: send-an-email
          params:
            body_text: 'Build failure in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
            subject_text: 'Build failure in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}' 
    
  - name: push-to-pks
    public: false
    serial: true
    plan:
      - get: yelb-github
        passed:
        - build-db-image
        - build-ui-image
        - build-appserver-image
        trigger: true
      - task: pks-get-kubeconfig
        file: yelb-github/pipelines/tasks/pks-get-kubeconfig.yml
        params:
          PKS: ((use-pks))
          PKS_API: ((pks-api))
          PKS_USERNAME: ((k8s-username))
          PKS_PASSWORD: ((k8s-password))
          PKS_CLUSTER: ((k8s-cluster))
          K8S_NAMESPACE: ((k8s-namespace))

    on_error:
      do:
        - put: send-an-email
          params:
            body_text: 'Build error in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
            subject_text: 'Build error in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
    on_failure:
      do:
        - put: send-an-email
          params:
            body_text: 'Build failure in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
            subject_text: 'Build failure in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}' 
    
    on_success:
      do:
        - put: send-an-email
          params:
            body_text: 'Build success in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
            attachment_globs: yelb-deployment
            subject_text: 'Build success in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
