---
resource_types:
  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource
  
  - name: k8s
    type: docker-image
    source:
      repository: frodenas/k8s-resource

resources:
  - name: yelb-github
    type: git
    icon: github-circle
    source:
      uri: https://github.com/devulrix/yelb.git
      branch: master

  - name: db-image
    type: docker-image
    source:
      username: ((harbor-user))
      password: ((harbor-password))
      repository: ((harbor-repo))/yelb-db

  - name: ui-image
    type: docker-image
    source:
      username: ((harbor-user))
      password: ((harbor-password))
      repository: ((harbor-repo))/yelb-ui

  - name: appserver-image
    type: docker-image
    source:
      username: ((harbor-user))
      password: ((harbor-password))
      repository: ((harbor-repo))/yelb-appserver
  
  - name: pks-k8s
    type: k8s
    source:
      url: ((k8s-url))
      skip_tls_verify: true
      token: ((k8s-token))
      namespace: ((k8s-namespace))
      debug: true
  
  - name: send-an-email
    type: email
    source: 
      from: ((mail-from))
      smtp: 
        host: ((mail-host))
        port: ((mail-port))
        username: ((mail-user))
        password: ((mail-password))
      to: [ ((mail-recipient)) ]


jobs:
  - name: build-db-image
    public: false
    serial: true
    plan: 
      - get: yelb-github
        trigger: true
      - put: db-image
        params:
          build: ./yelb-github/yelb-db 
  
  - name: build-ui-image
    public: false
    serial: true
    plan:
      - get: yelb-github
        trigger: true
      - put: ui-image
        params:
          build: ./yelb-github/yelb-ui

  - name: build-appserver-image
    public: false
    serial: true
    plan:
      - get: yelb-github
        trigger: true
      - put: appserver-image
        params:
          build: ./yelb-github/yelb-appserver

    on_error:
      do:
        - put: send-an-email
          params:
            body_text: 'Build error in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
            subject_text: 'Build error in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
    on_failure:
      do:
        - put: send-an-email
          params:
            body_text: 'Build failure in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
            subject_text: 'Build failure in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}' 
    
  - name: push-to-pks
    public: false
    serial: true
    plan:
      - get: yelb-github
      - get: db-image
        trigger: true
        passed: [build-db-image]
      - get: ui-image
        trigger: true
        passed: [build-ui-image]
      - get: appserver-image
        trigger: true
        passed: [build-appserver-image]
      - put: pks-k8s
        params:
          spec_path: ./yelb-github/deployments/platformdeployment/Kubernetes/yaml/pks-yelb-lb-harbor.yaml

    on_error:
      do:
        - put: send-an-email
          params:
            body_text: 'Build error in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
            subject_text: 'Build error in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
    on_failure:
      do:
        - put: send-an-email
          params:
            body_text: 'Build failure in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
            subject_text: 'Build failure in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}' 
    
    on_success:
      do:
        - put: send-an-email
          params:
            body_text: 'Build success in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
            subject_text: 'Build success in concourse: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}'
