{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "yelb.serviceAccountName" . }}
  labels:
{{ include "yelb.labels" . | nindent 4 }}
{{- end -}}
